### ISSUE TITLE
Use staging settings in dev.echaloasuerte

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/deployment#108]
## Background
We use two environment variables to define the environment where the app will be running
#### NODE_ENV
Used to decide the type of server that we will be starting.
If NODE_ENV == `production` a production-like server is used. Technically it will be the same
if NODE_ENV != `production` a development server is used. This server is not meant to be used in production as it's watching the files for changes, doing hot reloading, etc

Possible values:
 - `production`
 - anything else

#### REACT_APP_ENV
Used to decide some settings such whether Google should index pages or which account the analytics events should be sent.

Possible values:
 - production (currently any deployed app, both in the prod and dev server)
 - local (running locally)
 - test (running battery tests)

## What needs to be done
Right now we are [always using the production settings in the deployed app](https://github.com/etcaterva/eas-frontend/blob/a76dbf8e12581a1f437589fedf8bf34184bb499b/Dockerfile-prod#L18) (both in prod and dev).
We want to set that variable to `REACT_APP_ENV=staging` when deploying to dev.echaloasuerte.com

**Comment by palvarez89** [comment]
Does this variable need to be set before doing `npm run build` or is enough if it's present at `npm start` time?

**Comment by dnaranjo89** [comment]
it's necessary on both steps

**Comment by palvarez89** [comment]
Implemented as part of https://github.com/etcaterva/eas-frontend/pull/170

@dnaranjo89: If you want me to, I can do the same for master branch?
