### ISSUE TITLE
Remove trailing slash from urls to eas3

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/deployment#112]
Remove the trailing slash from incoming urls when redirecting to eas3 (or at least to nextjs)
E.g: 
Convert:`https://echaloasuerte.com/groups/`
To: `https://echaloasuerte.com/groups`

https://www.digitalocean.com/community/questions/how-do-i-get-nginx-to-remove-trailing-and-characters

**Comment by palvarez89** [comment]
I'm hoping that https://github.com/etcaterva/deployment/commit/8a3c009771b61ce63a712a6f133f7d96bfeb69ea fixes the issue. Thanks for the link!

**Comment by palvarez89** [comment]
I need a way of testing this :S

**Comment by palvarez89** [comment]
Confirmed that it works, thanks @dnaranjo89!
