### ISSUE TITLE
Url to static files go to the wrong location

### ISSUE THREAD

**Issue by dnaranjo89** [etcaterva/deployment#113]
We are see a lot of 404s to static files.
This is an example: https://echaloasuerte.com/static/media/groups_og_image.bda19441.png

The URL above sometimes leads to a 404.

It seems to happen when the user has the cookie to go to nextjs

**Comment by dnaranjo89** [comment]
For refference, these are the two types of urls for static files:
- Nextjs: `https://echaloasuerte.com/_next/static/images/groups_og_image-0019b44442eb1e5713da2001b8f93014.png`
- CRA: `https://echaloasuerte.com/static/media/raffle_og_image.4ed9b050.png`

**Comment by dnaranjo89** [comment]
I don't know why users in B would be requesting assets from A tho...

**Comment by palvarez89** [comment]
I don't understand either what can cause this issue (cross static-fila usage), but I've reproduced it.

Trying something that might fix it.

**Comment by palvarez89** [comment]
In theory this should fix it: https://github.com/etcaterva/deployment/commit/1e23910ceff27c431f5b796e75491c293331a1f4

But https://dev.echaloasuerte.com looks a bit broken with it, maybe unrelated?

**Comment by palvarez89** [comment]
Fixed with https://github.com/etcaterva/deployment/commit/e28a3d22d9afbfabed5abc12f966261dce97e14c
