### ISSUE TITLE
Purge postgres database

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/deployment#118]
Well, there is too much data in there. We need to investigate what is using that much space, and do some cleanups.

I found this useful: https://wiki.postgresql.org/wiki/Disk_Usage

**Comment by mariocj89** [comment]
A good start would be to add an index to the created_at field in the models, to allow deleting old entries.

**Comment by mariocj89** [comment]
Work to be done:

- [ ] Create index in created_at to facilitate delete by date.
- [ ] Ensure all tables have delete-from configured to facilitate the purge.
- [ ] Write a script to delete (private?) draws older than a year.

**Comment by palvarez89** [comment]
`created_at` index changes are now in prod

**Comment by mariocj89** [comment]
Done in the hackathon
