### ISSUE TITLE
Change eas-frontend sentry to use the eas-backend account

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/deployment#119]
Where does the DSN, and more config lives? Is it the same for backend/frontend?

Nothing coming through, fix it!

**Comment by mariocj89** [comment]
I think we need to change the current account to use the echaloasuerte email, as right now I configured it and only I see the alerts.

I tried adding more people, but that requires a business account.

**Comment by mariocj89** [comment]
Done, moved to echaloasuerte, see the password in our sheet.

**Comment by mariocj89** [comment]
> Where does the DSN, and more config lives? Is it the same for backend/frontend?

I;d expect for it to be in the vault and it injects it via env var. See https://github.com/etcaterva/eas-backend/blob/master/eas/settings/prod.py#L26

**Comment by palvarez89** [comment]
Yes, I found that one too, but we need to sort this for the frontend

**Comment by mariocj89** [comment]
@dnaranjo89 moved frontend sentry
