### ISSUE TITLE
Deploy async secret santa

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/deployment#123]
- [x] Land https://github.com/etcaterva/eas-backend/pull/103.
- [x] Change EAS_MAIL_PASSWORD to the AWS password.
- [x] Run docker with rabitmq in dev and prod.
- [x] run celery task

**Comment by palvarez89** [comment]
Rabbitmq not running on docker. Celery task managed by systemd, could be improved following celery docs about how to do it.

We could do with some monitoring
