### ISSUE TITLE
Initial deployment support for EAS 3.0

### ISSUE THREAD

**Issue by palvarez89** [etcaterva/deployment#74]
Current plan is to have an initial deployment of the new version of EAS so that new draws are handled by it, but legacy ones still go through the old frontend.

The integration idea would be:
- docker for backend if feasible in current servers.
- frontend compiled in static files at deployment time. As simple as possible but doing it inside docker would be handy and clean. 
- nginx to decide which frontend to use depending on the URL
- nginx to configure new frontend as a single page app

In addition to this integration, it would be nice to have for development purposes a script to only deploy the new app (front + back)

Note: this doesn't have to be perfect, but has to be done soon.

**Comment by mariocj89** [comment]
Where will the scripts for deployment live? This repository shared with the previous version?
