### ISSUE TITLE
uwsgi logs are misconfigured

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/deployment#85]
At the moment the logs being generated by uwsgi in [here](https://github.com/etcaterva/deployment/blob/b0dab49bfcbb0fd8901eacd85574d9171542eb6e/roles/echaloasuerte-3/templates/echaloasuerte-uwsgi.ini#L12) and [here](https://github.com/etcaterva/deployment/blob/f29f7f1edf3aa529a5be913d88784e8769e9f487/roles/echaloasuerte/templates/echaloasuerte-uwsgi.ini#L12) are ever growing and dont have read permission for other.

We should probably rotate and purge them or find any other way to limit the size of them and change the permissions to allow any user to read them (or add all our users to a group that can read them).

At the moment, eas2 logs take 3GB in the disk.

**Comment by palvarez89** [comment]
Sent a PR to limit size of the logs. I'll think a bit about the permissions, I didn't consider that being a problem, but I agree that using sudo should be avoided.
