### ISSUE TITLE
Export database from prod to dev 

### ISSUE THREAD

**Issue by mariocj89** [etcaterva/deployment#98]
Exporting the db will allow us to:

- Gain confidence on the new code working wiht the prod data
- allow us to check the data easier by enabling the admin mode in dev

**Comment by mariocj89** [comment]
Not relevant anymore as we implemented a custom way of doing backups in the backend.

**Comment by palvarez89** [comment]
Even though backups are done by the backend, they needed some orchestration. This has been done now as part of:

https://github.com/etcaterva/deployment/commit/86347fd4cb525b6ed3d434d64c79ad74e190da99
https://github.com/etcaterva/deployment/commit/b4c809e586cbca7de94ec4ce51e1006200d2c282
